### ISSUE TITLE
Additional features

### ISSUE THREAD

**Issue by sumith1896** [rupanshuganvir/cpp-matrixlibrary#3]
**Direct constructors**

Direct constructors for some special matrices come very handy in libraries. You can code up for identity and diagonals

```
identity(5);
```

will generate a 5x5 identity matrix

```
diag[3, 2, 1];
```

will generate a diagonal matrix with diagonal elements as 3, 2 and 1.

**Determinant**

Determinants are always found in libraries.  I don't know how hard it will be to implement but if implemented will be a great feature.

**Comment by theQmech** [comment]
1)
Say identity(5) can be generated as matrix<T> P(5,5,1)

2)
T A[]={3,2,1}
matrix<T> Q=diag(A,3) will give desired output.

Thanks for the suggestions.

**Comment by sumith1896** [comment]
Determinant?

**Comment by rupanshuganvir** [comment]
Determinant has also been added.

**Comment by theQmech** [comment]
Determinant has also been added.
